name: Github Push back to gitea

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pikaos-linux/pikaos-builder:nestv3
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:

    - uses: actions/checkout@v3

    - name: Is github check
      run: echo "${PWD##*/}" | grep "gitea-pika-first-setup" || exit 1

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Run
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: ./.github/github_pushback.sh
